apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-03-11T02:00:32Z"
  labels:
    app.kubernetes.io/name: argocd-server
    pod-template-hash: 7dbdcc97b9
  name: argocd-server
  namespace: argocd
  resourceVersion: "200871"
  uid: e7fe9e98-ca6e-42aa-b23c-50a70cdc62cf
spec:
  clusterIP: 10.43.62.126
  clusterIPs:
  - 10.43.62.126
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32182
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/name: argocd-server
    pod-template-hash: 7dbdcc97b9
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
