apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio
    spec:
      containers:
        - name: my-portfolio
          image: hoffeloffe/my-portfolio:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-portfolio-service
spec:
  selector:
    app: my-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
