server {
    listen 3000 default_server;
    listen [::]:3000 default_server;
    
    root /usr/share/nginx/html;
    index index.html index.htm;
    
    server_name _;
    
    # Debian nginx doesn't use io_setup by default
    # so we don't need to explicitly disable it
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    # Handle resume file download
    location /files/ {
        add_header Content-Disposition "attachment";
    }
    
    # Error handling
    error_page 404 /index.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
