apiVersion: v1
kind: ConfigMap
metadata:
  name: website-content
  namespace: my-app  # Specify the namespace
data:
  index.html: |
    <html>
      <body>
        <h1>Hello, K3s!</h1>
      </body>
    </html>
