apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
  namespace: my-app  # Specify the namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
