apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-website-ingress
  namespace: my-app  # Specify the namespace
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: 192.168.0.139  # Replace with your node's IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-website
            port:
              number: 80
