apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
  namespace: my-app  # Specify the namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
        - name: static-website
          image: nginx:alpine  # Using the default NGINX image
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-volume
              mountPath: /usr/share/nginx/html  # Mount path where NGINX looks for files
      volumes:
        - name: website-volume
          configMap:
            name: website-config  # This is the ConfigMap we created earlier
