apiVersion: v1
kind: ConfigMap
metadata:
  name: website-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>My Website</title>
    </head>
    <body>
        <h1>Welcome to My Website!</h1>
        <p>This is served using NGINX from a Kubernetes ConfigMap.</p>
    </body>
    </html>
