apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
        - name: static-website
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-content-volume
              mountPath: /usr/share/nginx/html  # NGINX default path for serving HTML
      volumes:
        - name: website-content-volume
          configMap:
            name: website-content  # The name of your ConfigMap
