apiVersion: v1
kind: ConfigMap
metadata:
  name: website-config
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>My Website</title>
      </head>
      <body>
        <h1>Welcome to My Website!</h1>
      </body>
    </html>
  server.js: |
    console.log("Server is running!");
