apiVersion: v1
kind: Service
metadata:
  name: static-website
  namespace: my-app  # Specify the namespace
spec:
  selector:
    app: static-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Expose the service outside the cluster
