name: Deprecated - Docker Build and Push

on:
  workflow_dispatch:

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - name: Docker workflow deprecated
        run: >-
          echo "This workflow is deprecated. Use CI + Infra + Deploy Dev/Prod workflows instead."
